---
# tasks file for mongo

- name: apt方式安装mongodb
  apt:
    name: mongodb
    update_cache: true

- name: 标记配置文件是否已被修改
  shell: cat /etc/mongodb.conf | grep 'bind_ip = 0.0.0.0'
  ignore_errors: True
  register: result

- name: 修改配置文件，ip绑定相关
  lineinfile:
    path: /etc/mongodb.conf
    regexp: '^bind_ip ='
    line: bind_ip = 0.0.0.0
  when: result.rc == 1
  notify: restart mongo